# Generated by Django 3.1.5 on 2021-01-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excellapp', '0002_client_client_notify_client_request_client_suggestion_faculty_det_fin_report_proj_company_proj_sts_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_mobile',
            field=models.IntegerField(null=True),
        ),
    ]
