# Generated by Django 3.1.5 on 2021-01-25 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excellapp', '0003_auto_20210125_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clients',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excellapp.userprofile'),
        ),
        migrations.AddField(
            model_name='client_notify',
            name='clients',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excellapp.userprofile'),
        ),
        migrations.AddField(
            model_name='client_request',
            name='clients',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excellapp.userprofile'),
        ),
        migrations.AddField(
            model_name='client_suggestion',
            name='clients',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excellapp.userprofile'),
        ),
        migrations.AddField(
            model_name='fin_report',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excellapp.staff'),
        ),
        migrations.AddField(
            model_name='proj_company',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excellapp.client'),
        ),
        migrations.AddField(
            model_name='proj_sts',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excellapp.client'),
        ),
        migrations.AddField(
            model_name='remark',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excellapp.student'),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excellapp.userprofile'),
        ),
        migrations.AddField(
            model_name='staff_attend',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excellapp.staff'),
        ),
        migrations.AddField(
            model_name='staff_joballoc',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excellapp.staff'),
        ),
        migrations.AddField(
            model_name='stu_attend',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excellapp.student'),
        ),
        migrations.AddField(
            model_name='stu_leave',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excellapp.student'),
        ),
        migrations.AddField(
            model_name='stu_pro_sts',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excellapp.student'),
        ),
        migrations.AddField(
            model_name='stu_suggestion',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excellapp.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excellapp.userprofile'),
        ),
    ]
