# Generated by Django 3.1.5 on 2021-01-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excellapp', '0005_auto_20210126_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_request',
            name='approved',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
