# Generated by Django 3.1.5 on 2021-01-26 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excellapp', '0006_client_request_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_request',
            name='clients',
        ),
        migrations.AddField(
            model_name='client_request',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='excellapp.client'),
            preserve_default=False,
        ),
    ]
